stages:
  - clean
  - build
  - test

clean:
  stage: clean
  script:
    - make clean

build:
  stage: build
  script:
    - echo "Nothing to do now."

test1:
  stage: test
  script:
    - make unit_test_1

test2:
  stage: test
  script:
    - make unit_test_2

test3:
  stage: test
  script:
    - make unit_test_3