stages:
  - clean
  - build
  - test

clean:
  stage: clean
  script:
    - make clean

build:
  stage: build
  script:
    - make code

test1:
  stage: test
  script:
    - make unit_test_1

test2:
  stage: test
  script:
    - make unit_test_2

test3:
  stage: test
  script:
    - make unit_test_3

test5:
  stage: test
  script:
    - make unit_test_5
